# ssh-keygen -t rsa -b 4096 -C orma/openroads-vn-analytics -f deploy_key
version: 2
jobs:
  build:
    docker:
      - image: node:6

    working_directory: ~/repo

    environment:
      - DEPLOY_BRANCH: "master"
      - SSH_URL: "ubuntu@ec2-13-229-8-3.ap-southeast-1.compute.amazonaws.com"

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test
      - run: yarn lint

      - add_ssh_keys:
          fingerprints:
            - "e6:d4:06:ff:b7:3b:39:01:ae:47:12:2d:b4:a1:97:fb"

      - run: 
          name: Processing translations
          command: |
            if [ "${CIRCLE_BRANCH}" == "${DEPLOY_BRANCH}" ]; then
              chmod +x ./.build_scripts/translations.sh
              ./.build_scripts/translations.sh
            else
              echo "Skip translations"
            fi

      - run: 
          name: Building site
          command: |
            if [ "${CIRCLE_BRANCH}" == "${DEPLOY_BRANCH}" ]; then
              yarn build
            else
              echo "Skip building site"
            fi

      - run:
          name: Deploy to AWS
          command: |
            if [ "${CIRCLE_BRANCH}" == "${DEPLOY_BRANCH}" ]; then
              cd dist
              ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $SSH_URL rm -rf /var/www/html/*
              scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -rp ./* $SSH_URL:/var/www/html
            else
              echo "Skip deploying to AWS"
            fi